name: Test tap-oracle

on: [push]

jobs:
  test:
    name: "Run tap-oracle on py${{ matrix.python-version }} (OS: ${{ matrix.os }}, Driver: ${{ matrix.oracle-driver }})"
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.9"]
        os: ["ubuntu-latest"]
        #oracle-driver: ["CX","THIN","THICK"]
        oracle-driver: ["THIN"]
    services:
      oracle:
        #image: container-registry.oracle.com/database/express:21.3.0-xe
        image: container-registry.oracle.com/database/free:23.2.0.0
        env:
          ORACLE_PWD: admin  # SYS, SYSTEM and PDBADMIN password
        ports:
          - 1521:1521

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Oracle Client
      if: matrix.oracle-driver != 'THIN'
      run: |
        apt-get update \
        && apt-get install -y unzip libaio1 \
        && apt-get clean \
        && find /var/cache/apt/archives /var/lib/apt/lists -not -name lock -type f -delete
      
  
        # Install the Oracle Client
        mkdir /opt/oracle \
        && cd ~ \
        && curl -O https://download.oracle.com/otn_software/linux/instantclient/1912000/instantclient-basic-linux.x64-19.12.0.0.0dbru.zip \
        && unzip instantclient-basic-linux.x64-19.12.0.0.0dbru.zip -d /opt/oracle \
        && rm instantclient-basic-linux.x64-19.12.0.0.0dbru.zip
    - name: Install tap in meltano
      run: |
        pip install meltano
        meltano init testproj
        cd testproj
        meltano add extractor tap-oracle --from-ref ../tap-oracle.yml || cat /home/runner/work/pipelinewise-tap-oracle/pipelinewise-tap-oracle/testproj/.meltano/logs/pip/extractors/tap-oracle/pip.log
        meltano invoke tap-oracle --discover
      env:
        TAP_ORACLE_HOST: localhost
        TAP_ORACLE_PORT: 1521
        TAP_ORACLE_PASSWORD: admin
        TAP_ORACLE_USER: SYS
        TAP_ORACLE_SERVICE_NAME: FREEPDB1
        TAP_ORACLE_ORA_PYTHON_DRIVER_TYPE: ${{ matrix.oracle-driver }}
        #ORACLE_HOME: /opt/oracle/instantclient_19_12
        #PATH: $PATH:$ORACLE_HOME
        #LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$ORACLE_HOME
        #TNS_ADMIN: $ORACLE_HOME/network/admin