name: Test tap-oracle

on: [push]

jobs:
  test:
    name: "Run tap-oracle on py${{ matrix.python-version }} (OS: ${{ matrix.os }}, Driver: ${{ matrix.oracledriver }})"
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.9"]
        os: ["ubuntu-latest"]
        oracle-driver: ["CX","THIN","THICK"]
    services:
      oracle:
        #image: container-registry.oracle.com/database/express:21.3.0-xe
        image: container-registry.oracle.com/database/free:23.2.0.0
        env:
          ORACLE_PWD: admin  # SYS, SYSTEM and PDBADMIN password
        ports:
          - 1521:1521

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tap
      run: |
        pip install .
    - name: Run a test discovery
      run: |
        tap-oracle --discover
      env:
        TAP_ORACLE_HOSTNAME: localhost
        TAP_ORACLE_PORT: 1521
        TAP_ORACLE_PASS: admin
        TAP_ORACLE_USER: SYS
        TAP_ORACLE_SERVICE_NAME: FREEPDB1
        TAP_ORACLE_ORA_PYTHON_DRIVER_TYPE: ${{ matrix.oracle-driver }}
